# Generated by Django 5.0.2 on 2024-04-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastf1_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastestpositionmodel',
            name='driver',
            field=models.IntegerField(default=1),
        ),
    ]
