# Generated by Django 5.0.2 on 2024-02-17 13:47

import extentions.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=120, unique=True, verbose_name='ایمیل')),
                ('fullname', models.CharField(max_length=34, validators=[extentions.validations.is_persian], verbose_name='نام کامل')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='نام کاربری')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال ؟')),
                ('is_ban', models.BooleanField(db_index=True, default=False, verbose_name='محدود شده ؟')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین ؟')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('v', 'وی ای پی'), ('p', 'پرو'), ('f', 'رایگان')], default='f', max_length=2, verbose_name='سطح کاربری')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='auth_user_set', related_query_name='user', to='auth.group', verbose_name='گروه ها')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='auth_user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
