# Generated by Django 5.0.2 on 2024-02-17 17:42

import ckeditor_uploader.fields
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته بندی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('parent_category', models.CharField(default='-', max_length=50, verbose_name='دسته بندی مادر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('position', models.IntegerField(verbose_name='جایگاه')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی پست',
                'verbose_name_plural': 'دسته\u200cبندی پست ها',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام')),
                ('description', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('slug', models.SlugField(verbose_name='آدرس پست')),
                ('publish_time', models.DateTimeField(default=datetime.datetime(2024, 2, 17, 17, 42, 28, 235625, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان نوشتن')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین تغییر')),
                ('is_active', models.BooleanField(default=True, verbose_name='پست نشان داده شود؟')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='محتوای صفحه')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس پست')),
                ('category', models.ManyToManyField(to='blog.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='کاربر')),
                ('text', models.TextField(verbose_name='متن کامنت')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت کامنت')),
                ('approved_comment', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
    ]
