# Generated by Django 5.0.2 on 2024-02-17 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 17, 43, 32, 674773, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
