# Generated by Django 5.0.2 on 2024-02-18 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 18, 11, 43, 831883, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
