# Generated by Django 5.0.2 on 2024-02-18 18:44

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته بندی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('parent_category', models.CharField(default='-', max_length=50, verbose_name='دسته بندی مادر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('position', models.IntegerField(verbose_name='جایگاه')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی پادکست',
                'verbose_name_plural': 'دسته\u200cبندی پادکست ها',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام')),
                ('description', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('slug', models.SlugField(verbose_name='آدرس پادکست')),
                ('publish_time', models.DateTimeField(default=datetime.datetime(2024, 2, 18, 18, 44, 50, 183140, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان نوشتن')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین تغییر')),
                ('is_active', models.BooleanField(default=True, verbose_name='پادکست نشان داده شود؟')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='محتوای صفحه')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس پادکست')),
                ('sound', models.FileField(upload_to='', verbose_name='پادکست')),
                ('category', models.ManyToManyField(to='podcast.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'پادکست',
                'verbose_name_plural': 'پادکست ها',
            },
        ),
    ]
