# Generated by Django 5.0.2 on 2024-02-18 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 18, 48, 20, 808792, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
