# Generated by Django 5.0.2 on 2024-02-17 13:47

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(max_length=450, verbose_name='رفرش توکن')),
                ('expired_at', models.DateTimeField(verbose_name='زمان منقضی شدن')),
                ('device_name', models.CharField(max_length=64, verbose_name='نام دستگاه')),
                ('ip_address', models.GenericIPAddressField(verbose_name='ادرس ip')),
                ('last_login', models.DateTimeField(verbose_name='اخرین ورود')),
            ],
            options={
                'verbose_name': 'ورود کاربر',
                'verbose_name_plural': 'ورود کاربران',
            },
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
